-- CreateEnum
CREATE TYPE "RaceStatus" AS ENUM ('REGISTERING', 'STARTED', 'ENDED');

-- AlterTable
ALTER TABLE "Race" ADD COLUMN "STATUS" "RaceStatus" NOT NULL DEFAULT 'REGISTERING';

-- Backfill existing races
UPDATE "Race" SET "STATUS" = 'ENDED' WHERE "IS_CLOSED" = 1;
UPDATE "Race" SET "STATUS" = 'STARTED' WHERE "START_TIME" IS NOT NULL AND ("IS_CLOSED" IS NULL OR "IS_CLOSED" != 1);
