-- AlterTable
ALTER TABLE "PrizeSchemeItem" ADD COLUMN "ID_RACE_TYPE" INTEGER;

-- AddForeignKey
ALTER TABLE "PrizeSchemeItem" ADD CONSTRAINT "PrizeSchemeItem_ID_RACE_TYPE_fkey" FOREIGN KEY ("ID_RACE_TYPE") REFERENCES "RaceType"("ID_RACE_TYPE") ON DELETE SET NULL ON UPDATE CASCADE;
