ALTER TYPE "NotificationKind" ADD VALUE IF NOT EXISTS 'RACE_REMINDER';
ALTER TYPE "NotificationKind" ADD VALUE IF NOT EXISTS 'BET_PROMPT';
ALTER TYPE "NotificationKind" ADD VALUE IF NOT EXISTS 'PAYMENT_RISK';
