ALTER TABLE "EventInventory" ADD COLUMN "ID_TEAM" INTEGER;
CREATE INDEX "EventInventory_ID_TEAM_idx" ON "EventInventory"("ID_TEAM");
ALTER TABLE "EventInventory" ADD CONSTRAINT "EventInventory_ID_TEAM_fkey" FOREIGN KEY ("ID_TEAM") REFERENCES "Team"("ID_TEAM") ON DELETE SET NULL ON UPDATE CASCADE;
