-- AlterTable
ALTER TABLE "Events" ADD COLUMN     "CONTACT_ADDRESS" TEXT,
ADD COLUMN     "CONTACT_EMAIL" TEXT,
ADD COLUMN     "CONTACT_NAME" TEXT,
ADD COLUMN     "CONTACT_PHONE" TEXT,
ADD COLUMN     "CONTACT_WEBSITE" TEXT,
ADD COLUMN     "DESCRIPTION" TEXT,
ADD COLUMN     "END_DATE" TIMESTAMP(3),
ADD COLUMN     "LOCATION_ADDRESS" TEXT,
ADD COLUMN     "SEASON_ID" INTEGER,
ADD COLUMN     "SOCIAL_FB" TEXT,
ADD COLUMN     "SOCIAL_INSTA" TEXT,
ADD COLUMN     "SOCIAL_TWITTER" TEXT,
ADD COLUMN     "SOCIAL_YT" TEXT;

-- AlterTable
ALTER TABLE "OrganizerData" ADD COLUMN     "USER_ID" TEXT;

-- CreateTable
CREATE TABLE "Seasons" (
    "id" SERIAL NOT NULL,
    "name" TEXT NOT NULL,
    "startDate" TIMESTAMP(3) NOT NULL,
    "endDate" TIMESTAMP(3) NOT NULL,
    "isActive" BOOLEAN NOT NULL DEFAULT false,

    CONSTRAINT "Seasons_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "OrganizerData_USER_ID_key" ON "OrganizerData"("USER_ID");

-- AddForeignKey
ALTER TABLE "OrganizerData" ADD CONSTRAINT "OrganizerData_USER_ID_fkey" FOREIGN KEY ("USER_ID") REFERENCES "Users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Events" ADD CONSTRAINT "Events_SEASON_ID_fkey" FOREIGN KEY ("SEASON_ID") REFERENCES "Seasons"("id") ON DELETE SET NULL ON UPDATE CASCADE;
